---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami-charts.yaml
  - ./bjw-s-charts.yaml
  - ./dysnix-charts.yaml
  - ./external-dns-charts.yaml
  - ./hajimari-charts.yaml
  - ./ingress-nginx-charts.yaml
  - ./jetstack-charts.yaml
  - ./kubereboot-charts.yaml
  - ./k8s-gateway-charts.yaml
  - ./metallb-charts.yaml
  - ./metrics-server-charts.yaml
  - ./stakater-charts.yaml
  - ./traefik-charts.yaml
  - ./gitlab-charts.yaml
  - ./hashicorp-charts.yaml
  - ./istio-charts.yaml
  - ./jaegertracing-charts.yaml
  - ./kiali-charts.yaml
  - ./codecentric-charts.yaml
  - ./kubernetes-dashboard.yaml
  - ./weave-gitops.yaml
